[package]
name = "nurl"
version = "0.3.7"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "Generate Nix fetcher calls from repository URLs"
readme = "README.md"
homepage = "https://github.com/nix-community/nurl"
repository = "https://github.com/nix-community/nurl"
license = "MPL-2.0"
keywords = ["cli", "fetch", "git", "nix", "prefetch"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.69"
bstr = "1.2.0"
enum_dispatch = "0.3.11"
git-url = "0.13.1"
itertools = "0.10.5"
once_cell = "1.17.0"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
rustc-hash = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
ureq = { version = "2.6.2", features = ["json"] }

[dependencies.clap]
version = "4.1.4"
features = ["cargo", "derive", "unicode", "wrap_help"]

[build-dependencies]
clap = { version = "4.1.4", features = ["derive"] }
clap_complete = "4.1.1"
clap_mangen = "0.2.7"

[dev-dependencies]
assert_cmd = "2.0.8"
nu-glob = "0.75.0"
trycmd = "0.14.11"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
